# @package habitat.dataset


defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: MP3DEQA-v1
split: train
data_path: "data/datasets/eqa/mp3d/v1/{split}/{split}.json.gz"
scenes_dir: "data/scene_datasets/"
