# @package habitat.simulator.agents.depth_head_depth_arm_agent

defaults:
  - agent_base
  - /habitat/simulator/sim_sensors@sim_sensors.head_depth_sensor: head_depth_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.arm_depth_sensor: arm_depth_sensor