# @package habitat.task
defaults:
  - /habitat/task/rearrange: rearrange_easy_base
  - override /habitat/task/actions:
    - arm_action
    - base_velocity_non_cylinder
    - rearrange_stop
actions:
  arm_action:
    grip_controller: GazeGraspAction
