# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: PointNav-v1
split: train_extra_large
data_path: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
