# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - arm_action
  - _self_

# No task logic, empty task
type: RearrangeEmptyTask-v0
actions:
  arm_action:
    grip_controller: "MagicGraspAction"
